tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/php"
brew "awscli"
brew "go"
brew "figlet"
brew "gifsicle"
brew "git"
brew "git-lfs"
brew "python"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "nmap"
brew "p7zip"
brew "packer"
brew "pandoc"
brew "pv"
brew "rclone"
brew "rsync"
brew "serverless"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "terraform"
brew "tmux"
brew "tox"
brew "wget"
brew "youtube-dl"
cask "1password"
cask "cura-lulzbot"
cask "docker"
cask "firefox"
cask "font-jetbrains-mono"
cask "font-ubuntu-mono-derivative-powerline"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hazel"
cask "postman"
cask "powershell"
cask "slack"
cask "textexpander"
cask "transmit"
cask "vagrant"
cask "vagrant-vmware-utility"
cask "visual-studio-code"
cask "vmware-fusion"
mas "GarageBand", id: 682658836
mas "iFlicks", id: 408937559
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Things", id: 904280696
mas "Xcode", id: 497799835
