tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "readline"
brew "sqlite"
brew "xz"
brew "ansible-lint"
brew "awscli"
brew "azure-cli"
brew "coreutils"
brew "figlet"
brew "gh"
brew "gifsicle"
brew "git"
brew "gnu-sed"
brew "go"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "nmap"
brew "node"
brew "p7zip"
brew "packer"
brew "pngquant"
brew "poetry"
brew "pre-commit"
brew "pyenv"
brew "rclone"
brew "rsync"
brew "shellcheck"
brew "terraform"
brew "terraform-docs"
brew "tmux"
brew "tox"
brew "wget"
brew "yamllint"
brew "youtube-dl"
brew "zopfli"
cask "1password"
cask "bettertouchtool"
cask "daisydisk"
cask "docker"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hazel"
cask "keyboard-maestro"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "notion"
cask "onedrive"
cask "postman"
cask "slack"
cask "transmit"
cask "vagrant"
cask "vagrant-vmware-utility"
cask "visual-studio-code"
cask "vmware-fusion"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
